apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: default
spec:
  replicas: 2  # количество реплик для отказаустойчивости 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web 
          image: nginx
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:      # Выделение ресурсов для приложения
              cpu: "0.5"       
              memory: 128Mi
            requests:
              cpu: "0.1"
              memory: 128Mi
          ports:
          - containerPort: 80

 # Проброс порта на внешку для доступа
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 32180
  selector:
    app: web
  type: NodePort

# Автосоздание реплик при нагрузке на CPU более 80%
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80